
{'responses': [{'responseId': 'ACYDBNjDTD4GiXpjbVHqnUSP8hRdpgIV-xXBY-3HISspXB4LYvhOV-QDVSE_r7EeGkhUU7Q',
                'createTime': '2022-04-09T18:43:11.452Z',
                'lastSubmittedTime': '2022-04-09T18:43:11.452719Z',
                'answers': {'0f000001': {'questionId': '0f000001',
                                         'textAnswers': {'answers': [{'value': '3'}]}},
                            '0f000000': {'questionId': '0f000000',
                                         'textAnswers': {'answers': [{'value': '2'}]}},
                            '0fffffff': {'questionId': '0fffffff',
                                         'textAnswers': {'answers': [{'value': 'so much for'}]}},
                            '0f000002': {'questionId': '0f000002',
                                         'textAnswers': {'answers': [{'value': '8'}]}}}},
               {'responseId': 'ACYDBNjLa9jyQIl5lyawkxEjf5NKhmxyFWvSWqKbvvj06SR48FGeRGsAlPaZ4MGcoYclStM',
                'createTime': '2022-04-09T18:43:19.930Z',
                'lastSubmittedTime': '2022-04-09T18:43:19.930303Z',
                'answers': {'0f000001': {'questionId': '0f000001',
                                         'textAnswers': {'answers': [{'value': '8'}]}},
                            '0f000000': {'questionId': '0f000000',
                                         'textAnswers': {'answers': [{'value': '2'}]}},
                            '0fffffff': {'questionId': '0fffffff',
                                         'textAnswers': {'answers': [{'value': 'loving you'}]}},
                            '0f000002': {'questionId': '0f000002',
                                         'textAnswers': {'answers': [{'value': '1'}]}}}},
               {'responseId': 'ACYDBNiT6Sm8DBh4js1pj23cKPNlUT83NxUBw8JizF1ek3ZPNkqjftytyi0_t6OdVGWKgOs',
                'createTime': '2022-04-09T18:43:01.293Z',
                'lastSubmittedTime': '2022-04-09T18:43:01.293999Z',
                'answers': {'0f000001': {'questionId': '0f000001',
                                         'textAnswers': {'answers': [{'value': '1'}]}},
                            '0f000000': {'questionId': '0f000000',
                                         'textAnswers': {'answers': [{'value': '2'}]}},
                            '0fffffff': {'questionId': '0fffffff',
                                         'textAnswers': {'answers': [{'value': 'avelyn'}]}},
                            '0f000002': {'questionId': '0f000002',
                                         'textAnswers': {'answers': [{'value': '2'}]}}}}]}

##########################################################################################################################################################################################################

{'formId': '14NX8cA816CPqz2ScefyhTs86kRzw1iU-rkTs_4EsPvg',
 'info': {'title': 'Easter test - input order',
          'description': 'Please enter your orders for Easter test bakesale.',
          'documentTitle': 'Easter test - input order'},
 'revisionId': '00000005',
 'responderUri': 'https://docs.google.com/forms/d/e/1FAIpQLSdelsUC3up97AeM8C__eRt5w1cj4_pWhY1-6kjI5u7EhZuWQQ/viewform',
 'items': [{'itemId': '7fbdcf74',
            'title': 'What is your name?',
            'questionItem': {'question': {'questionId': '0fffffff',
                                          'required': True,
                                          'textQuestion': {}}}},
           {'itemId': '565c732c',
            'title': 'How much cake would you like? -enter 0 if none-',
            'questionItem': {'question': {'questionId': '0f000000',
                                          'required': True,
                                          'textQuestion': {}}}},
           {'itemId': '4024a390',
            'title': 'How much coke would you like? -enter 0 if none-',
            'questionItem': {'question': {'questionId': '0f000001',
                                          'required': True,
                                          'textQuestion': {}}}},
           {'itemId': '72b7219e',
            'title': 'How much balloon would you like? -enter 0 if none-',
            'questionItem': {'question': {'questionId': '0f000002',
                                          'required': True,
                                          'textQuestion': {}}}}]}

##########################################################################################################################################################################################################

{'jolie': {'cake': 10}, 'Alex': {'cookie': 5} }


{
   '575b14df': {'questionId': '575b14df',
                'textAnswers': {'answers': [{'value': 'Shi Hao'}]}},
   '41353c3b': {'questionId': '41353c3b',
                'textAnswers': {'answers': [{'value': '0'}]}},
   '1c372859': {'questionId': '1c372859',
                'textAnswers': {'answers': [{'value': '2'}]}},
   '41bb848d': {'questionId': '41bb848d',
                'textAnswers': {'answers': [{'value': '3'}]}}}


##########################################################################################################################################################################################################

{'responses':
 [{'responseId': 'ACYDBNjpOtps-3aUo6Ru1j8yHGj399-pg47My1j4zdF8melTPT1lPLUptRzqsLGPYiBeTJY',
   'createTime': '2022-04-06T21:08:20.508Z',
   'lastSubmittedTime': '2022-04-06T21:08:20.508655Z',
   'answers': {'77fe7314': {'questionId': '77fe7314',
                            'textAnswers': {'answers': [{'value': '2'}]}},
               '522f5be3': {'questionId': '522f5be3',
                            'textAnswers': {'answers': [{'value': 'New-order'}]}},
               '10ba62c5': {'questionId': '10ba62c5',
                            'textAnswers': {'answers': [{'value': '2'}]}},
               '55da2389': {'questionId': '55da2389',
                            'textAnswers': {'answers': [{'value': '3'}]}},
               '11b18998': {'questionId': '11b18998',
                            'textAnswers': {'answers': [{'value': 'Yes'}]}}}},
  {'responseId': 'ACYDBNil9Hq4_QMawNuc7Hxyhavx17uLk3N4Lrs96fEODFxJHQH7Twijp1Ky-ILtd-cH9AM',
   'createTime': '2022-04-06T21:09:47.173Z',
   'lastSubmittedTime': '2022-04-06T21:09:47.173135Z',
   'answers': {'4c281c64': {'questionId': '4c281c64',
                            'textAnswers': {'answers': [{'value': '0'}]}},
               '2741ddd0': {'questionId': '2741ddd0',
                            'textAnswers': {'answers': [{'value': '0'}]}},
               '522f5be3': {'questionId': '522f5be3',
                            'textAnswers': {'answers': [{'value': 'Pre-order'}]}},
               '2f2a62b1': {'questionId': '2f2a62b1',
                            'textAnswers': {'answers': [{'value': 'Alex'}]}},
               '746beab1': {'questionId': '746beab1',
                            'textAnswers': {'answers': [{'value': 'Yes'}]}},
               '1850d2c4': {'questionId': '1850d2c4',
                            'textAnswers': {'answers': [{'value': '2'}]}}}},
  {'responseId': 'ACYDBNgzvfsN1JaxW6E456MSBhmBeIMKmkPQgnG5WSw32jY1klfIlJB5KWPn7_GxNVxU0Dk',
   'createTime': '2022-04-06T21:10:35.659Z',
   'lastSubmittedTime': '2022-04-06T21:10:35.659791Z',
   'answers': {'522f5be3': {'questionId': '522f5be3',
                            'textAnswers': {'answers': [{'value': 'Pre-order'}]}},
               '7e0d1ef4': {'questionId': '7e0d1ef4',
                            'textAnswers': {'answers': [{'value': '2'}]}},
               '02d40a92': {'questionId': '02d40a92',
                            'textAnswers': {'answers': [{'value': 'Yes'}]}},
               '2f2a62b1': {'questionId': '2f2a62b1',
                            'textAnswers': {'answers': [{'value': 'Nimbus'}]}},
               '6f753632': {'questionId': '6f753632',
                            'textAnswers': {'answers': [{'value': '2'}]}},
               '4ddc009a': {'questionId': '4ddc009a',
                            'textAnswers': {'answers': [{'value': '1'}]}}}},
  {'responseId': 'ACYDBNgbTCHkJhgdcUkK1T-c0K-zp2HQhGNxyrhJFnHmis6SEQyP6K9I-mF70_XGxLmRDis',
   'createTime': '2022-04-06T21:09:16.712Z',
   'lastSubmittedTime': '2022-04-06T21:09:16.712063Z',
   'answers': {'77fe7314': {'questionId': '77fe7314',
                            'textAnswers': {'answers': [{'value': '2'}]}},
               '522f5be3': {'questionId': '522f5be3',
                            'textAnswers': {'answers': [{'value': 'New-order'}]}},
               '10ba62c5': {'questionId': '10ba62c5',
                            'textAnswers': {'answers': [{'value': '2'}]}},
               '55da2389': {'questionId': '55da2389',
                            'textAnswers': {'answers': [{'value': '3'}]}},
               '11b18998': {'questionId': '11b18998',
                            'textAnswers': {'answers': [{'value': 'Yes'}]}}}},
  {'responseId': 'ACYDBNgI90Csc8jxH3IcWI-3uBqXPFw8N_r2kiW8ddUQ2FHLucEhW1mNbSqpGjjU4cMGI4g',
   'createTime': '2022-04-06T21:09:32.940Z',
   'lastSubmittedTime': '2022-04-06T21:09:32.940351Z',
   'answers': {'6be328ad': {'questionId': '6be328ad',
                            'textAnswers': {'answers': [{'value': '10'}]}},
               '522f5be3': {'questionId': '522f5be3',
                            'textAnswers': {'answers': [{'value': 'Pre-order'}]}},
               '2f2a62b1': {'questionId': '2f2a62b1',
                            'textAnswers': {'answers': [{'value': 'Jolie'}]}},
               '74fd748f': {'questionId': '74fd748f',
                            'textAnswers': {'answers': [{'value': '2'}]}},
               '58f43f33': {'questionId': '58f43f33',
                            'textAnswers': {'answers': [{'value': 'Yes'}]}},
               '52e10b8a': {'questionId': '52e10b8a',
                            'textAnswers': {'answers': [{'value': '2'}]}}}},
  {'responseId': 'ACYDBNgYYbnTrXv8nUOHqlpnOPQewf1y_sxm27QZn8PYW9aSArY6i0Wq__nSuwFXQGsjsWc',
   'createTime': '2022-04-06T21:09:05.097Z',
   'lastSubmittedTime': '2022-04-06T21:09:05.097567Z',
   'answers': {'77fe7314': {'questionId': '77fe7314',
                            'textAnswers': {'answers': [{'value': '2'}]}},
               '522f5be3': {'questionId': '522f5be3',
                            'textAnswers': {'answers': [{'value': 'New-order'}]}},
               '10ba62c5': {'questionId': '10ba62c5',
                            'textAnswers': {'answers': [{'value': '3'}]}},
               '55da2389': {'questionId': '55da2389',
                            'textAnswers': {'answers': [{'value': '0'}]}},
               '11b18998': {'questionId': '11b18998',
                            'textAnswers': {'answers': [{'value': 'Yes'}]}}}}]}

##########################################################################################################################################################################################################

{'formId': '1ZTjMR1nbheQYuzqSAdpjTG9Uy2lkD37qmRiZBbR8kJg',
 'info': {'title': 'Easter bakesale - sell order',
          'documentTitle': 'Easter bakesale - sell order'},
 'revisionId': '00000006',
 'responderUri': 'https://docs.google.com/forms/d/e/1FAIpQLSeMbJI7GAkOcJGii0asjKBbSCV1G9winIyokpYqq72yPf0AgQ/viewform',
 'items': [{'itemId': '62716b05',
            'title': 'Is this a pre-order or a new-order? Please Select.',
            'questionItem': {'question': {'questionId': '522f5be3',
                                          'required': True,
                                          'choiceQuestion': {'type': 'RADIO',
                                                             'options': [{'value': 'Pre-order',
                                                                          'goToSectionId': '0fffffff'},
                                                                         {'value': 'New-order',
                                                                          'goToSectionId': '0eeeeeee'}]}}}},
           {'itemId': '0fffffff',
            'pageBreakItem': {},
            'title': 'Pre ordered',
            'description': 'Here is the list of names of people who has pre-ordered products. Please choose the correct name.'},
           {'itemId': '0f3e2ec2',
            'title': 'Choose the name of the pupil who had pre-ordered.',
            'questionItem': {'question': {'questionId': '2f2a62b1',
                                          'required': True,
                                          'choiceQuestion': {'type': 'DROP_DOWN',
                                                             'options': [{'value': 'Jolie',
                                                                          'goToSectionId': '0a000000'},
                                                                         {'value': 'Alex',
                                                                          'goToSectionId': '0a000001'},
                                                                         {'value': 'Chloe',
                                                                          'goToSectionId': '0a000002'},
                                                                         {'value': 'Nimbus',
                                                                          'goToSectionId': '0a000003'}]}}}},
           {'itemId': '0eeeeeee',
            'pageBreakItem': {},
            'title': 'New order',
            'description': 'Enter what are the products and the amount that has been ordered by the pupil. If none just enter 0.'},
           {'itemId': '1e6a3479',
            'title': 'cake',
            'questionItem': {'question': {'questionId': '10ba62c5',
                                          'textQuestion': {}}}},
           {'itemId': '59aa877b',
            'title': 'coke',
            'questionItem': {'question': {'questionId': '55da2389',
                                          'textQuestion': {}}}},
           {'itemId': '139a31c7',
            'title': 'balloon',
            'questionItem': {'question': {'questionId': '77fe7314',
                                          'textQuestion': {}}}},
           {'itemId': '449fedc1',
            'title': 'Please confirm that you are creating a new order.',
            'questionItem': {'question': {'questionId': '11b18998',
                                          'required': True,
                                          'choiceQuestion': {'type': 'RADIO',
                                                             'options': [{'value': 'Yes',
                                                                          'goToAction': 'SUBMIT_FORM'},
                                                                         {'value': 'No',
                                                                          'goToAction': 'RESTART_FORM'}]}}}},
           {'itemId': '0a000000',
            'pageBreakItem': {},
            'title': 'Jolie',
            'description': 'Products ordered: cake = 10, coke = 0, balloon = 0.'},
           {'itemId': '30d2aca5',
            'title': 'cake',
            'questionItem': {'question': {'questionId': '6be328ad',
                                          'textQuestion': {}}}},
           {'itemId': '3dc215d9', 'title': 'coke',
            'questionItem': {'question': {'questionId': '52e10b8a',
                                          'textQuestion': {}}}},
           {'itemId': '25c1da2b',
            'title': 'balloon',
            'questionItem': {'question': {'questionId': '74fd748f',
                                          'textQuestion': {}}}},
           {'itemId': '1f156e8e',
            'title': 'Please confirm that this is Jolie.',
            'questionItem': {'question': {'questionId': '58f43f33',
                                          'required': True,
                                          'choiceQuestion': {'type': 'RADIO',
                                                             'options': [{'value': 'Yes',
                                                                          'goToAction': 'SUBMIT_FORM'},
                                                                         {'value': 'No',
                                                                          'goToAction': 'RESTART_FORM'}]}}}},
           {'itemId': '0a000001',
            'pageBreakItem': {},
            'title': 'Alex',
            'description': 'Products ordered: cake = 0, coke = 0, balloon = 0.'},
           {'itemId': '6ca0d76a',
            'title': 'cake',
            'questionItem': {'question': {'questionId': '1850d2c4',
                                          'textQuestion': {}}}},
           {'itemId': '44c34c4f',
            'title': 'coke',
            'questionItem': {'question': {'questionId': '4c281c64',
                                          'textQuestion': {}}}},
           {'itemId': '473f4b66',
            'title': 'balloon',
            'questionItem': {'question': {'questionId': '2741ddd0',
                                          'textQuestion': {}}}},
           {'itemId': '50f31cb3',
            'title': 'Please confirm that this is Alex.',
            'questionItem': {'question': {'questionId': '746beab1',
                                          'required': True,
                                          'choiceQuestion': {'type': 'RADIO',
                                                             'options': [{'value': 'Yes',
                                                                          'goToAction': 'SUBMIT_FORM'},
                                                                         {'value': 'No',
                                                                          'goToAction': 'RESTART_FORM'}]}}}},
           {'itemId': '0a000002',
            'pageBreakItem': {},
            'title': 'Chloe',
            'description': 'Products ordered: cake = 2, coke = 0, balloon = 2.'},
           {'itemId': '6adceeb2',
            'title': 'cake',
            'questionItem': {'question': {'questionId': '69016743',
                                          'textQuestion': {}}}},
           {'itemId': '490f08ad',
            'title': 'coke',
            'questionItem': {'question': {'questionId': '4404094c',
                                          'textQuestion': {}}}},
           {'itemId': '0765b2a6',
            'title': 'balloon',
            'questionItem': {'question': {'questionId': '2fdf476e',
                                          'textQuestion': {}}}},
           {'itemId': '64b84f4d',
            'title': 'Please confirm that this is Chloe.',
            'questionItem': {'question': {'questionId': '5d5e1310',
                                          'required': True,
                                          'choiceQuestion': {'type': 'RADIO',
                                                             'options': [{'value': 'Yes',
                                                                          'goToAction': 'SUBMIT_FORM'},
                                                                         {'value': 'No',
                                                                          'goToAction': 'RESTART_FORM'}]}}}},
           {'itemId': '0a000003',
            'pageBreakItem': {},
            'title': 'Nimbus',
            'description': 'Products ordered: cake = 0, coke = 0, balloon = 0.'},
           {'itemId': '48f6e23e',
            'title': 'cake',
            'questionItem': {'question': {'questionId': '6f753632',
                                          'textQuestion': {}}}},
           {'itemId': '7a6a4330',
            'title': 'coke',
            'questionItem': {'question': {'questionId': '4ddc009a',
                                          'textQuestion': {}}}},
           {'itemId': '545f3692',
            'title': 'balloon',
            'questionItem': {'question': {'questionId': '7e0d1ef4',
                                          'textQuestion': {}}}},
           {'itemId': '068f7486',
            'title': 'Please confirm that this is Nimbus.',
            'questionItem': {'question': {'questionId': '02d40a92',
                                          'required': True,
                                          'choiceQuestion': {'type': 'RADIO',
                                                             'options': [{'value': 'Yes',
                                                                          'goToAction': 'SUBMIT_FORM'},
                                                                         {'value': 'No',
                                                                          'goToAction': 'RESTART_FORM'}]}}}}]}























